# Microprocessor-and-Microcontroller
ORG 0000H
SETB P0.0 ;TO SET THE PORTS
SETB P0.1
SETB P0.2
READ:MOV C,P0.0 ;MOVE P0.0 TO C
CPL C ;COMPLEMENT C
MOV 00H,C
MOV C,P0.1
CPL C
ORL C,00H ;IMPLEMENT OR OPERATION
CPL C
MOV P0.2,C
SJMP READ ;JUMP TO READ
END
